services:
  rfid-service:
    build:
      dockerfile: Dockerfile
    container_name: rfid-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka-broker:9092
      - SPRING_APPLICATION_NAME=rfid-emulator
